### ISSUE TITLE
usb.core.NoBackendError: No backend available

### ISSUE THREAD

**Issue by FilippoGiombi** [Ziiipple2022/iPwndfu_2022#1]
Hi, i want to use ipwndfu on my iPhone 6, I followed all the instructions, I already installed libusb with homebrew, but I get this error. Can you help me?

Here is the complete error:
![Screenshot 2023-02-13 alle 18 23 42](https://user-images.githubusercontent.com/66132931/218530140-44497bd9-cb5f-4480-b3da-5c7486a7d606.png)

**Comment by Ziiipple2022** [comment]
Reinstall LibUSB and follow tutorial for install Python with Pyenv

**Comment by AnInsomniacy** [comment]
same problem,already install peen and correct python
